# Generated by Django 4.2.3 on 2023-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_factura_cloud_name_alter_factura_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
