# Generated by Django 4.2.3 on 2023-07-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_alter_factura_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadofactura',
            name='name',
            field=models.CharField(blank=True, help_text='Nombre que tendra el listado de esta factura', max_length=255, null=True),
        ),
    ]
